### ISSUE TITLE
Deprecated 'set-output' print in start time example

### ISSUE THREAD

**Issue by andersonshatch** [Contrast-Security-OSS/integration-verify-github-action#203]
In the README example, the following section:

```yaml
        # record start time so we can verify only newly found vulnerabilities
      - name: Define job start time
        run: |
          import time
          n = int(round(time.time() * 1000))
          print(f"::set-output name=jobStartTime::{n}")
        shell: python
        id: set-job-start-time
```
Yields a deprecation warning:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
